### ISSUE TITLE
Discord or similar?

### ISSUE THREAD

**Issue by F0x1fy** [ericlass/erc#7]
Hello!

I was wondering if there were any ways for community interaction such as Discord. I'd love to learn more about the language and discuss more in-depth about it. I understand there's currently a small community, but I'm still interested nonetheless!

**Comment by ericlass** [comment]
Hi. Thanks for reaching out. There is no place for discussion yet. The language is still in very early stages. On top of that, I recently got invited to take part in another project, so process on erc will be very limited in the next months. But it's a good idea and I'll set up a Discord once I can focus my efforts on erc again.

**Comment by F0x1fy** [comment]
Hello ericlass,

Thank you for the response! I'll be keeping an eye out for any updates regarding erc and a Discord. I was interesting in looking at the compiler as well, as I am designing my own programming language for my senior capstone. Any features in particular that you're proud of or anything in particular to keep in mind when looking at the source?

**Comment by ericlass** [comment]
Sure. I'll do some stuff now and then.

The one feature I really want erc to have is the built-in vector types. In GPU shader languages like GLSL you have those and all modern CPUs also have vector units. But no CPU targeting language has these supported via built-in types, at least none that I know of. Sure, in C++ you have intrinstics and the "__m128" kind of types and other do vectorization, but it's not really a core feature. So, that's the feature I see stading out.
