### ISSUE TITLE
Multiple Return Values

### ISSUE THREAD

**Issue by F0x1fy** [ericlass/erc#8]
Hello,

I was wondering if multiple return values has been considered for this language. It would, however, require a change in the calling convention.

**Comment by ericlass** [comment]
I thought about multiple return values a few times. I like the idea. I would probably go with the tuple approach, something like `return (a, b);`, simlar to Rust. But that would be a feature for after the 1.0 version.

**Comment by F0x1fy** [comment]
How do you envision the syntax? For example, in Odin, it's:
```
x, y := foo();
```
Would you take a similar approach or something different?

**Comment by ericlass** [comment]
First thought was
```
(x, y) = foo();
```
Though, I kinda like it without brackets. I think I would go without.
